name: CI


on:

  pull_request:
    branches: [ "DEV" ]
    types: [closed ]
  workflow_dispatch:
    inputs:
      job:
        description: 'Despliegues'
        required: true
        default: 'merge-dev-to-pre'
jobs:
  merge-dev-to-pre:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge dev -> pre
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: DEV
          target_branch: PRE
          github_token: ${{ github.token }}
  merge-pre-to-pro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge pre ->  pro
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: PRE
          target_branch: PRO
          github_token: ${{ github.token }}

