name: CI


on:

  pull_request:
    branches: [ "DEV" ]
    types: [closed ]
  workflow_dispatch:
    inputs:
      job:
        description: 'Despliegues'
        required: true
        default: 'merge-dev-to-pre'
jobs:

  merge-dev-to-pre:
    runs-on: ubuntu-latest
    environment: PRE
    steps:
      - uses: actions/checkout@master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          base: DEV
          branch: PRE
          delete-branch: false
      # uses: devmasx/merge-branch@master
      # with:
      #   type: now
      #    from_branch: DEV
      #    target_branch: PRE
      #    github_token: ${{ github.token }}
  merge-pre-to-pro:
    runs-on: ubuntu-latest
    environment: main
    needs: merge-dev-to-pre
    steps:
      - uses: actions/checkout@master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          base: PRE
          branch: main
          delete-branch: false
      #- name: Merge pre ->  pro
      #  uses: devmasx/merge-branch@master
      #  with:
      #    type: now
      #    from_branch: PRE
      #    target_branch: main
      #    github_token: ${{ github.token }}

